---
version: "3.6"

# The slim version of opa bundle server monitor
networks:
    monitor:
        driver: bridge

services:
    opa-bundle:
        depends_on:
            - demo-server
        image: openpolicyagent/opa:latest
        container_name: opa-bundle
        hostname: opa-bundle
        restart: always
        volumes:
            - ./opa/config-bundle.yaml:/code/config-bundle.yaml
        ports:
            - "8181:8181"
        networks:
            - monitor
        command: run -s -a :8181 -c /code/config-bundle.yaml
    opa-discovery:
        depends_on:
            - demo-server
        image: openpolicyagent/opa:latest
        container_name: opa-discovery
        hostname: opa-discovery
        restart: always
        volumes:
            - ./opa/config-discovery.yaml:/code/config-discovery.yaml
        ports:
            - "8182:8182"
        networks:
            - monitor
        command: run -s -a :8182 -c /code/config-discovery.yaml
    demo-server:
        image: golang:1.19.5-alpine
        container_name: golang
        restart: always
        volumes:
            # the `go build` way (skip `go mod download` during start)
            - ./demo-server/demo-app:/code/demo-app
            - ./demo-server/rbac.tar.gz:/code/rbac.tar.gz
            - ./demo-server/discovery.tar.gz:/code/discovery.tar.gz
            # the `go run main.go opa.go` way
            # - ./demo-server/.go-cache/pkg/mod:/go/pkg/mod
        ports:
            - "8888:8888"
        networks:
            - monitor
        env_file: ./demo-server/revision.env
        working_dir: /code
        entrypoint: ["/code/demo-app"]
    # collecting opa-bundle and other metrics
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        restart: always
        volumes:
            - ./prometheus/prometheus-slim.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        networks:
            - monitor
